"""init user model

Revision ID: 07a02f7163a3
Revises: 
Create Date: 2025-01-11 03:02:42.780426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07a02f7163a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('RESIDENT', 'STAFF', 'ADMIN', name='role').create(op.get_bind())
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('RESIDENT', 'STAFF', 'ADMIN', name='role', create_type=False), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    sa.Enum('RESIDENT', 'STAFF', 'ADMIN', name='role').drop(op.get_bind())
    # ### end Alembic commands ###
