"""add suspended

Revision ID: 138785bdc79d
Revises: 07a02f7163a3
Create Date: 2025-01-11 16:18:14.327041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138785bdc79d'
down_revision: Union[str, None] = '07a02f7163a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('suspended', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspended')
    # ### end Alembic commands ###
