"""rename desc to justification

Revision ID: 207834ab2959
Revises: 306d60368f1d
Create Date: 2025-01-17 17:32:19.478623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207834ab2959'
down_revision: Union[str, None] = '306d60368f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_users', sa.Column('justification', sa.String(), nullable=True))
    op.drop_column('task_users', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_users', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task_users', 'justification')
    # ### end Alembic commands ###
