"""add orders

Revision ID: 29b276aba922
Revises: d7914c838e5c
Create Date: 2025-01-12 16:05:24.845532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29b276aba922'
down_revision: Union[str, None] = 'd7914c838e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'CLAIMED', name='orderstate').create(op.get_bind())
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'CLAIMED', name='orderstate', create_type=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    op.drop_table('orders')
    sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'CLAIMED', name='orderstate').drop(op.get_bind())
    # ### end Alembic commands ###
