"""add description

Revision ID: 306d60368f1d
Revises: 90123f8ae3df
Create Date: 2025-01-17 17:17:14.242262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306d60368f1d'
down_revision: Union[str, None] = '90123f8ae3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_users', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('voucher_tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voucher_tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('task_users', 'description')
    # ### end Alembic commands ###
