"""add description

Revision ID: 90123f8ae3df
Revises: dfa96de9f599
Create Date: 2025-01-17 01:42:48.478266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90123f8ae3df'
down_revision: Union[str, None] = 'dfa96de9f599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher_tasks', sa.Column('description', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher_tasks', 'description')
    # ### end Alembic commands ###
