"""actually add products

Revision ID: d7914c838e5c
Revises: 5ad0780ec189
Create Date: 2025-01-11 23:32:01.664227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7914c838e5c'
down_revision: Union[str, None] = '5ad0780ec189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FOOD', 'NONFOOD', 'SPECIAL', name='category').create(op.get_bind())
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', postgresql.ENUM('FOOD', 'NONFOOD', 'SPECIAL', name='category', create_type=False), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    sa.Enum('FOOD', 'NONFOOD', 'SPECIAL', name='category').drop(op.get_bind())
    # ### end Alembic commands ###
